config/routes.rb
Rails.application.routes.draw do
  resources :todos

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  #validates
  #before_save :downcase_title
  #validates
  #validates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only:[:show, :edit, :update, :destroy]
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = 'your todo was crpeated'
      redirect_to todos_path
    else
      flash[:notice] = 'Oops something went wrong'
      render 'new'
    end
  end

  def update
    @todo = Todo.find(params[:id])
    if @todo.update_attributes(todo_params)
      flash[:notice] = 'your todo was update'
      redirect_to todos_path
    else
      flash[:notice] = 'Oops something went wrong'
      render 'new'
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id] )
  end

  def edit
    @todo = Todo.find(params[:id])

  end
  def set_todo
    @todo =Todo.find(params[:id])
  end

  private
  def todo_params
    params.require(:todo).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Totoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form_todo.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :todo %>
  <%= f.text_field :title %>
  <%= f.submit 'Submit'%>
<% end %>

<p><%= link_to "Index", todos_path %><p>

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>


<%= render partial: "form_todo" %>

app/views/todos/index.html.erb
<h1>Todos#index</h1>
<p>Find me in app/views/todos/index.html.erb</p>

<p><%= link_to "New Todo", new_todo_path %><p>

<ul style="width: 500px; ">
<% @todos.each do |todo| %>

    <li style ="border-bottom: black 1px solid; margin-bottom: 5px">
  <span> <%= todo.title %> </span>
  <span style="float: right"><%= link_to "Edit", edit_todo_path(todo.id) %><span> |
  <span style="float: right"><%= link_to " Delete", todo_path(todo.id), method: "delete" %><span>
  </li>
<% end %>
</ul>

app/views/todos/new.html.erb
<h1>Todos#new</h1>
<p>Find me in app/views/todos/new.html.erb</p>


<%= render partial: "form_todo" %>

app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>